services:
  web:
    image: nginx
    volumes:
      - /valya/home/php/docker/nginx/default.conf:/etc/nginx.conf:etc/nginx/conf.d/default.conf
      - /valya/home/php/docker:/var/www/html

  php-fpm:
    container_name: php-fpm
    build: .docker/docker_php
    volumes:
      - .:/var/www/html
      - .:/docker_php/xdebug.ini:/usr/local/etc/php/conf.d/docker_php-ext-xdebug.ini

  db:
    image: postgres:13.1
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 54322:5432